on: [push]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build project with Maven
        run: mvn clean install
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --enableRetired
        env:
          JAVA_HOME: /opt/jdk
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports
  slscan:
    runs-on: ubuntu-latest
    needs: depchecktest
    name: Perform SL Scan
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "credscan,java,depscan"
      - uses: actions/upload-artifact@master
        with:
          name: SLSCAN reports
          path: ${{github.workspace}}/reports
  generate-sbom:
      runs-on: ubuntu-latest
      needs: depchecktest
      name: Generate CycloneDX SBOM
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: setup-java
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'
            cache: 'maven'
        - name: Generate CycloneDX SBOM
          run: mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom
        - name: Upload CycloneDX SBOM
          uses: actions/upload-artifact@master
          with:
            name: BOM
            path: target/bom.xml  # 上傳 Maven 標準目錄中的 bom.xml 文件
  build_and_push:
    name: Build & Push to DockerHub
    needs: slscan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build with Maven
        run: mvn clean install
      - name: Docker Build and Push to DockerHub
        uses: docker/build-push-action@v5
        with:
            context: .
            push: true
            tags: 12qw412s/gitactiondependencycheck:1.0